import { useLocation } from "wouter";
import { ArrowRight, Check, ChevronDown, Code2, GitBranch, ShieldCheck, Sparkles, Zap, Activity, Network, BrainCircuit, PlayCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { toast } from "sonner";

const heroImage = "/manus-storage/qualityforge-observability-hero_8bb8bcd1.png";

export default function Home() {
  const [, setLocation] = useLocation();
  return <div className="landing-page"><header className="landing-nav"><button className="landing-brand" onClick={() => setLocation("/")}><span className="brand-mark"><span className="brand-mark-core" /></span><b>QualityForge</b><small>AI</small></button><nav><a href="#capabilities">Platform</a><a href="#intelligence">Intelligence</a><a href="#delivery">Delivery</a><a href="#pricing">Pricing</a></nav><div><button onClick={() => startLogin()} className="nav-login">Sign in</button><Button onClick={() => setLocation("/app")} className="nav-demo">Launch demo <ArrowRight /></Button></div></header>
    <main><section className="landing-hero"><div className="hero-grid" /><img className="hero-visual" src={heroImage} alt="Abstract QualityForge observability signal"/><div className="hero-copy"><p className="hero-kicker"><span /> Quality intelligence for modern engineering teams</p><h1>Ship with a <em>stronger signal.</em></h1><p className="hero-lede">QualityForge AI unifies test design, execution evidence, defect intelligence, and release readiness in one decisive engineering workspace.</p><div className="hero-actions"><Button onClick={() => setLocation("/app")} className="hero-primary">Explore the live demo <ArrowRight /></Button><button onClick={() => document.getElementById("capabilities")?.scrollIntoView({ behavior: "smooth" })} className="hero-secondary"><PlayCircle /> See how it works</button></div><div className="hero-proof"><span><Check /> AI-assisted test design</span><span><Check /> Delivery-quality gates</span><span><Check /> Built for engineering teams</span></div></div><div className="hero-status-card"><div><span className="live-dot" /> Release candidate</div><h3>2026.08.12-rc.3</h3><div className="mini-score"><b>92</b><span>QUALITY<br/>SCORE</span><i /></div><p><ShieldCheck /> Ready with mitigation</p></div></section>
      <section className="logo-strip"><p>Designed for the work between code complete and confident delivery.</p><div><span>TEST DESIGN</span><i /><span>DEFECT INTELLIGENCE</span><i /><span>RELEASE READINESS</span><i /><span>QUALITY GATES</span></div></section>
      <section className="landing-section capability-section" id="capabilities"><div className="section-intro"><p className="eyebrow">ONE CONNECTED QUALITY SYSTEM</p><h2>From feature intent to production confidence.</h2><p>QualityForge provides the shared operational surface teams need to design the right tests, understand failures, and make delivery decisions with evidence.</p></div><div className="capability-grid"><article className="capability-card feature"><span><Sparkles /></span><h3>AI test design</h3><p>Translate behavior, contracts, and acceptance criteria into editable functional, boundary, security, and regression scenarios.</p><a href="#intelligence">Design with intent <ArrowRight /></a></article><article className="capability-card"><span><Code2 /></span><h3>Execution clarity</h3><p>Orchestrate API, UI, integration, and regression runs with investigation-ready results.</p></article><article className="capability-card"><span><BrainCircuit /></span><h3>Defect intelligence</h3><p>Cluster recurring failures and guide root-cause analysis with the context that matters.</p></article><article className="capability-card"><span><GitBranch /></span><h3>Delivery control</h3><p>Connect quality evidence to CI/CD gates and explain why a release is ready, blocked, or watched.</p></article></div></section>
      <section className="signal-section" id="intelligence"><div className="signal-copy"><p className="eyebrow">AI-ASSISTED ENGINEERING WORKFLOWS</p><h2>Investigate the failure, not the noise.</h2><p>Forge Assistant gives test, defect, release, and pipeline data a shared language. Ask why an execution failed, which defects threaten a release, or where coverage needs to move next.</p><ul><li><Check /> Root-cause direction with evidence and confidence</li><li><Check /> Failure patterns grouped into actionable clusters</li><li><Check /> Regression recommendations tied to every fix</li></ul><Button onClick={() => setLocation("/app/assistant")} variant="outline">Meet Forge Assistant <ArrowRight /></Button></div><div className="signal-board"><div className="signal-board-header"><span><span className="pulse-live" /> AI failure intelligence</span><small>Last 24 hours</small></div><div className="signal-cluster hot"><span>01</span><div><small>HIGH IMPACT</small><b>Authentication failures</b><p>18 occurrences · 7 affected tests</p></div><em>Investigate <ArrowRight /></em></div><div className="signal-cluster"><span>02</span><div><small>WATCH</small><b>API timeout pattern</b><p>11 occurrences · 4 affected tests</p></div><em>Investigate <ArrowRight /></em></div><div className="signal-cluster"><span>03</span><div><small>WATCH</small><b>Validation mismatch</b><p>9 occurrences · 6 affected tests</p></div><em>Investigate <ArrowRight /></em></div><div className="signal-board-foot"><BrainCircuit /><p><b>AI observation:</b> Session revocation behavior changed after the latest identity deployment.</p></div></div></section>
      <section className="landing-section delivery-section" id="delivery"><div className="delivery-card"><div><p className="eyebrow">QUALITY GATES THAT EXPLAIN THEMSELVES</p><h2>Give every release a defensible verdict.</h2><p>QualityForge weights test evidence, automation coverage, system health, defect severity, and stability into a transparent readiness score.</p><Button onClick={() => setLocation("/app/releases")} className="hero-primary">See release readiness <ArrowRight /></Button></div><div className="delivery-score"><div className="delivery-ring"><b>92</b><small>/100</small></div><div><span>RELEASE READINESS</span><h3>Ready with mitigation</h3><p>Clear the payment contract defect before promotion.</p></div></div><div className="delivery-evidence"><span><i /> Test pass rate <b>93%</b></span><span><i /> Coverage <b>88%</b></span><span><i /> API health <b>97%</b></span><span><i className="warning" /> Critical defects <b>1</b></span></div></div></section>
      <section className="outcomes-section"><div><p className="eyebrow">THE QUALITY OPERATING MODEL</p><h2>Calm for the team.<br/><em>Clarity for delivery.</em></h2></div><div className="outcomes-grid"><article><Activity /><b>Unified release signal</b><p>Replace disconnected status rituals with measurable, traceable quality evidence.</p></article><article><Network /><b>Contract confidence</b><p>Build API checks alongside the workflows that rely on them, not after the defect appears.</p></article><article><Zap /><b>Faster failure response</b><p>Bring clustering, investigation notes, and next tests into the same operational moment.</p></article></div></section>
      <section className="pricing-section" id="pricing"><div className="section-intro center"><p className="eyebrow">SCALES WITH YOUR QUALITY PRACTICE</p><h2>Start with a signal. Grow into a system.</h2><p>Clear plans for teams moving from release confidence to coordinated quality operations.</p></div><div className="pricing-grid"><article><p className="plan-name">Foundation</p><h3>For teams building a shared quality baseline.</h3><b className="price">$29 <small>/ user / month</small></b><ul><li><Check /> Test case and execution management</li><li><Check /> API validation workspace</li><li><Check /> Release-readiness dashboard</li></ul><Button variant="outline" onClick={() => setLocation("/app")}>Explore demo</Button></article><article className="featured-plan"><span className="plan-ribbon">Most complete</span><p className="plan-name">Forge</p><h3>For delivery teams operating with AI quality intelligence.</h3><b className="price">$59 <small>/ user / month</small></b><ul><li><Check /> Everything in Foundation</li><li><Check /> AI test generation and defect analysis</li><li><Check /> Failure clustering and quality gates</li><li><Check /> Team and audit workflows</li></ul><Button onClick={() => setLocation("/app")}>Launch live demo <ArrowRight /></Button></article><article><p className="plan-name">Enterprise</p><h3>For organizations standardizing quality governance.</h3><b className="price">Let’s talk</b><ul><li><Check /> SSO and advanced access control</li><li><Check /> Custom quality policies</li><li><Check /> Dedicated implementation support</li></ul><Button variant="outline" onClick={() => toast("Enterprise contact workflow would open here.")}>Contact us</Button></article></div></section>
      <section className="faq-section"><div><p className="eyebrow">FAQ</p><h2>Quality operations,<br/>without the ambiguity.</h2></div><div>{[["Does QualityForge replace our test framework?", "No. QualityForge is the operating layer around the quality work your team already does. It organizes test design, execution evidence, defects, and release signals in one system."], ["Can we use it for API and UI automation?", "Yes. The platform is designed around API contract validation, browser automation concepts, integration tests, regression runs, and execution evidence."], ["How does the AI support engineers?", "AI features help turn context into test scenarios, summarize likely defect causes, identify recurring failure patterns, and explain release risk. Your team maintains ownership of final engineering decisions."], ["Can I explore it without setup?", "Yes. Launch the demo to explore a seeded quality workspace with projects, test cases, executions, defects, releases, and AI workflows."]].map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown /></summary><p>{answer}</p></details>)}</div></section>
      <section className="closing-cta"><div><p className="eyebrow">BETTER SIGNALS. BETTER RELEASES.</p><h2>Make quality your<br/><em>delivery advantage.</em></h2><p>Bring test evidence, failure intelligence, and release confidence together.</p><Button onClick={() => setLocation("/app")} className="hero-primary">Launch the live demo <ArrowRight /></Button></div><div className="cta-grid" /></section>
    </main><footer className="landing-footer"><button className="landing-brand" onClick={() => setLocation("/")}><span className="brand-mark"><span className="brand-mark-core" /></span><b>QualityForge</b><small>AI</small></button><p>AI-powered software quality intelligence for modern engineering teams.</p><span>© 2026 QualityForge AI</span></footer>
  </div>;
}
